### ISSUE TITLE
L10N of Payara Server Documentation

### ISSUE THREAD

**Issue by khasunuma** [payara/Payara-Server-Documentation#219]
I will localize Payara Server Documentation. _e.g._ Japanese, Germany

Then can you prepare the space on repository and reference to L10N documents?

Japanese developers are so happy if there is Japanese documentation, not only Payara but also any other softwares. I'll meet their expectations.

**Comment by OndrejM** [comment]
Hi @khasunuma, that's very kind of you and helpful indeed. We're very interested in Japanese users and we understand that English is not very accessible for them. However, we're now analyzing how we can support a Japanese translation in the long term so that it stays in line with the English one. 

I think the best thing we could do now is that you create your own copy of the repository and start translating to Japanese in that repository. Later we can setup a separate gitbook page from it, or merge it into the main documentation. What do you think?

**Comment by khasunuma** [comment]
Hello @OndrejM, I quite agree to your proposal.

**Comment by fturizo** [comment]
Closing this issue as localization is not yet in our plans for documentatin maintenance.
